[package]
name = "modulus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num = "0.4"
jni = "0.20.0"
[lib]
crate_type = ["cdylib"]


